services:
  postgres:
    image: postgres:18
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: irrigation
    ports:
      - "5432:5432"
    volumes:
      - irrigation-pgdata:/var/lib/postgresql
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "irrigation"]
      interval: 10s
      timeout: 5s
      retries: 10
  
  mqtt:
    image: eclipse-mosquitto:2.1.2-alpine
    container_name: mqtt-broker
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config:/mosquitto/config
    restart: unless-stopped
volumes:
  irrigation-pgdata: