// <auto-generated />
using System;
using IrrigationApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IrrigationApi.Migrations
{
    [DbContext(typeof(IrrigationContext))]
    [Migration("20260710074916_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IrrigationApi.Entities.IrrigationEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("ReadingIdEnd")
                        .HasColumnType("bigint")
                        .HasColumnName("reading_id_end");

                    b.Property<long?>("ReadingIdStart")
                        .HasColumnType("bigint")
                        .HasColumnName("reading_id_start");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<DateTimeOffset?>("StoppedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("stopped_at");

                    b.Property<int>("ZoneId")
                        .HasColumnType("integer")
                        .HasColumnName("zone_id");

                    b.HasKey("Id")
                        .HasName("pk_irrigation_events");

                    b.HasIndex("ReadingIdEnd")
                        .HasDatabaseName("ix_irrigation_events_reading_id_end");

                    b.HasIndex("ReadingIdStart")
                        .HasDatabaseName("ix_irrigation_events_reading_id_start");

                    b.HasIndex("ZoneId")
                        .HasDatabaseName("ix_irrigation_events_zone_id");

                    b.ToTable("irrigation_events", (string)null);
                });

            modelBuilder.Entity("IrrigationApi.Entities.SensorReading", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("Humidity")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("humidity");

                    b.Property<decimal?>("Moisture")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("moisture");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<decimal?>("Temperature")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("temperature");

                    b.Property<int>("ZoneId")
                        .HasColumnType("integer")
                        .HasColumnName("zone_id");

                    b.HasKey("Id")
                        .HasName("pk_sensor_readings");

                    b.HasIndex("ZoneId", "RecordedAt")
                        .HasDatabaseName("ix_sensor_readings_zone_id_recorded_at");

                    b.ToTable("sensor_readings", (string)null);
                });

            modelBuilder.Entity("IrrigationApi.Entities.Zone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("HasMoistureSensor")
                        .HasColumnType("boolean")
                        .HasColumnName("has_moisture_sensor");

                    b.Property<bool>("HasTempHumiditySensor")
                        .HasColumnType("boolean")
                        .HasColumnName("has_temp_humidity_sensor");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("ProfileId")
                        .HasColumnType("integer")
                        .HasColumnName("profile_id");

                    b.HasKey("Id")
                        .HasName("pk_zones");

                    b.HasIndex("ProfileId")
                        .HasDatabaseName("ix_zones_profile_id");

                    b.ToTable("zones", (string)null);
                });

            modelBuilder.Entity("IrrigationApi.Entities.ZoneProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CropType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("crop_type");

                    b.Property<decimal>("MaxMoisture")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("max_moisture");

                    b.Property<decimal>("MinMoisture")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("min_moisture");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("SoilType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("soil_type");

                    b.HasKey("Id")
                        .HasName("pk_zone_profiles");

                    b.ToTable("zone_profiles", (string)null);
                });

            modelBuilder.Entity("IrrigationApi.Entities.IrrigationEvent", b =>
                {
                    b.HasOne("IrrigationApi.Entities.SensorReading", "ReadingEnd")
                        .WithMany()
                        .HasForeignKey("ReadingIdEnd")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_irrigation_events_sensor_readings_reading_id_end");

                    b.HasOne("IrrigationApi.Entities.SensorReading", "ReadingStart")
                        .WithMany()
                        .HasForeignKey("ReadingIdStart")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_irrigation_events_sensor_readings_reading_id_start");

                    b.HasOne("IrrigationApi.Entities.Zone", "Zone")
                        .WithMany()
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_irrigation_events_zones_zone_id");

                    b.Navigation("ReadingEnd");

                    b.Navigation("ReadingStart");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("IrrigationApi.Entities.SensorReading", b =>
                {
                    b.HasOne("IrrigationApi.Entities.Zone", "Zone")
                        .WithMany()
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sensor_readings_zones_zone_id");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("IrrigationApi.Entities.Zone", b =>
                {
                    b.HasOne("IrrigationApi.Entities.ZoneProfile", "Profile")
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_zones_zone_profiles_profile_id");

                    b.Navigation("Profile");
                });
#pragma warning restore 612, 618
        }
    }
}
